import { enableTotp } from "@/apiAxios";
import { ResponseStatus } from "@/models/request";
import { useState } from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import { Button, Container, Input, Modal } from "reactstrap";

function TestTotp() {
  const navigate = useNavigate();
  const [code, setCode] = useState("");
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [modalOpen, setModalOpen] = useState(false);

  const handleSubmit = async () => {
    if (!code) {
      toast.error("Please enter a valid TOTP code.");
      return;
    }
    const res = await enableTotp({ code });
    if (res.data.status === ResponseStatus.ERROR) {
      toast.error(res.data.message);
    } else {
      toast.success("TOTP code verified successfully!");
      setBackupCodes(res.data.codes);
      setModalOpen(true);
    }
  };

  return (
    <Container>
      <h1 className="text-center mt-5">Test Two Factor Authentication Code</h1>
      <p className="text-center mt-3">
        Please enter the code generated by your authenticator app to test your
        Two-Factor Authentication setup.
      </p>
      <Input
        type="text"
        placeholder="Enter TOTP Code"
        className="mt-3"
        onChange={(e) => setCode(e.target.value)}
        value={code}
        autoFocus
      />
      <Button color="success" className="mt-3" onClick={handleSubmit}>
        Submit
      </Button>
      <Modal isOpen={modalOpen} toggle={() => setModalOpen(!modalOpen)}>
        {backupCodes.length > 0 && (
          <Container className="p-4 d-flex flex-column align-items-center">
            <h5>Backup Codes</h5>

            <div className="mt-3 mb-3">
              {backupCodes.map((code, index) => (
                <div key={index}>{code}</div>
              ))}
            </div>

            <p>
              Keep these codes safe, you can use them to access your account if
              you lose access to your authenticator app.
            </p>
            <p>
              This is the last time you will see these codes, so make sure to
              save them securely.
            </p>
            <Button
              color="success"
              onClick={() => {
                setModalOpen(false);
                navigate("/profile");
              }}
            >
              Close
            </Button>
          </Container>
        )}
      </Modal>
    </Container>
  );
}

export default TestTotp;
