import { verifyTotp } from "@/apiAxios";
import { ResponseStatus } from "@/models/request";
import { useState } from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import { Button, Container, Input } from "reactstrap";

function VerifyTotp() {
  const navigate = useNavigate();
  const [code, setCode] = useState("");

  const handleSubmit = async () => {
    if (!code) {
      toast.error("Please enter a valid two factor authentication code.");
      return;
    }
    const res = await verifyTotp({ code });
    if (res.data.status === ResponseStatus.ERROR) {
      toast.error(res.data.message);
    } else {
      toast.success("Two factor authentication code verified successfully!");
      localStorage.setItem("apiToken", res.data.token);
      navigate("/dashboard");
    }
  };

  return (
    <Container>
      <h1 className="text-center mt-5">
        You have two factor authentication enabled on your account
      </h1>
      <p className="text-center mt-3">
        Please enter the code generated by your authenticator app to verify your
        Two-Factor Authentication setup.
      </p>
      <Input
        type="text"
        placeholder="Enter TOTP Code"
        className="mt-3"
        onChange={(e) => setCode(e.target.value)}
        value={code}
        autoFocus
      />
      <Button color="success" className="mt-3" onClick={handleSubmit}>
        Submit
      </Button>
      <Container style={{ marginTop: "20px", paddingLeft: "0px" }}>
        <a
          href="/auth/lost-authenticator"
          style={{ fontWeight: "bold", color: "green" }}
        >
          I lost access to my authenticator app
        </a>
      </Container>
    </Container>
  );
}

export default VerifyTotp;
