
const acceptedFileTypesPhotos = ["image/png","image/jpg","image/jpeg","image/webp"]
const availableGames = [
'Chess',
'Monopoly',
'Scrabble',
'Risk',
'Settlers of Catan',
'Clue',
'Ticket to Ride',
'Uno',
'Battleship',
'Apples to Apples',
'Dominion',
'Puerto Rico',
'Yahtzee',
'Trivial Pursuit',
'Stratego',
'Checkers',
'Sorry!',
'Agricola',
'Carcassonne',
'Pictionary',
'Pandemic',
'Connect Four',
'Go',
'Backgammon',
'Arkham Horror',
'Axis and Allies',
'Power Grid',
'The Game of Life',
'Candyland',
'A Game of Thrones',
'Battlestar Galactica',
'Cosmic Encounter',
'Smallworld',
'Twilight Struggle',
'Trouble',
'Tigris and Euphrates',
'7 Wonders',
'Twilight Imperium',
'Chinese Checkers',
'Mastermind',
'Cranium',
'El Grande',
'Don’t Break the Ice',
'Scattergories',
'Dixit',
'Mahjong',
'Say Anything',
'Dominoes',
'Dominant Species',
'Cards Against Humanity',
'Guess Who?',
'Dungeon!',
'Reversi / Othello',
'Mancala',
'The Invasion of Canada',
'Taboo',
'Diplomacy',
'Descent: Journeys in the Dark',
'Hi Ho! Cherry-O',
'Wits and Wagers',
'Caylus',
'Key to the Kingdom',
'Chutes and Ladders',
'Blood Bowl',
'Uno Attack',
'Shogun',
'Operation',
'Through the Ages',
'Pay Day',
'Shadows Over Camelot',
'Alhambra',
'Balderdash',
'Le Havre',
'Acquire',
'Scotland Yard',
'Summoner Wars',
]

const dummyUser = {
    _id: "id",
    name: "name",
    email: "email",
    birthday: "birthday",
    gender: "gender",
    description: "",
    saidYesTo: [],
    saidNoTo: [],
    gamesSelected:[],

}

export {
    acceptedFileTypesPhotos,
    availableGames,
    dummyUser
}